- repo: git://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-lint
    - id: go-imports
    # go-cyclo will attempt to scan the generated grpc sources and fail
    # - id: go-cyclo
    #   args: [-over=15]
    - id: go-build