dist: bionic
language: go
go:
- 1.13.x
- master
- tip
os:
- linux
- osx
env: MOD=github.com/romnn/ldap-manager BINARY=ldap-manager
jobs:
  allow_failures:
  - go: tip
  fast_finish: true
  include:
  - stage: test
    name: Lint helm chart
    os: linux
    go: master
    script:
    - helm lint deployment/helm/charts/ldapmanager/

  - stage: deploy
    name: Publish release
    os: linux
    go: master
    script:
    - invoke cc
    deploy:
      provider: releases
      token:
        secure: p5fEZooVOWCVeIp8fgY5mvplE87LCXHCurf/M310RY2AHIIRsMQI2VtVhsZ5MzOno7cnYBGd5lGsci7VbwhbukWHPqiugXYgmkDbl/vTUotqGM5Lcp5ILUXMhpBST4vQGuc7Q4JmUxlgbil7dnV5qiaBg3MqMAfXJcS3aZ8lptQlflPJFJtJoNKtFqQwTuqukc7cVRlqzzTS6VU6Pm0Sna8c687ZCJcktc2lGddYoo7/HVUhaanFsQjrRUf7Fq9b4qjyF8JszrMptpeHDv7JTnzLQFVxzhrWPc/HFLJ/7DMCJPBhbIb9a0+HJOjGglmiztumuEtcL+qBQoWadyQqcnKG5+mcCI5xeP/3679CwutAoyc7+Fc10Wz6opFA7uiUQ9johEtpyX6wm16McB4lGgtxGeXGrIOat5QeMqMvwg826LoC6+7GElsu9qx+XbjmrRPR2h7x63sOuYf0GWT31xLCwSpkQ4Rt9ArZK1/1YyujJAULXiLXiDgT04wI+BjTzweUdg98SLMv5uip80qZE6FGIcxM1hPYs7lcR3fd9GTI48j2bwdU65pGsDKeHxyN+yh+6hAFOmd/0bFya3m9kBEbxdaGIcI1A6VE90BmHNJ1/DOaSaTT1+jLW72K9yqZ5HA2o2LhDBDS9kLqBUQPYQuLsqqaYy2w5Dv9JnOEpSg=
      file_glob: true
      file: build/*
      skip_cleanup: true
      on:
        repo: romnn/ldap-manager
        tags: true

  - stage: deploy
    name: Publish helm chart release
    os: linux
    go: master
    script:
    - touch ./public/.nojekyll
    - deployment/helm/charts/ldapmanager/add-repos.sh
    - helm package --dependency-update --destination ./public/charts deployment/helm/charts/ldapmanager
    - export TRAVIS_REPO_OWNER=${TRAVIS_REPO_SLUG%/*}
    - export TRAVIS_REPO_NAME=${TRAVIS_REPO_SLUG#*/}
    - helm repo index --url https://${TRAVIS_REPO_OWNER}.github.io/${TRAVIS_REPO_NAME}/charts ./public/charts
    python: 3.6
    deploy:
      provider: pages
      local_dir: public
      skip_cleanup: true
      # Generate a GitHub access token for public repositories
      # In your travis ci settings, set the token as a secret environment variable $GH_TOKEN
      token: "$GH_TOKEN"
      keep_history: true
      on:
        repo: romnn/ldap-manager
        tags: false
        branches:
          only:
            - master
install: true
notifications:
  email: false
before_script:
- pip install -U pip && pip install pre-commit invoke ruamel.yaml
- go get -u golang.org/x/lint/golint
- go get github.com/fzipp/gocyclo
- go get github.com/mitchellh/gox
- curl -L https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
script:
- env GO111MODULE=on go build -race ${MOD}
- invoke pre-commit
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then env GO111MODULE=on go test -v -race -coverprofile=coverage.txt -coverpkg=all -covermode=atomic ./... ; fi
after_success:
- bash <(curl -s https://codecov.io/bash)
