apiVersion: v1
entries:
  ldap-manager:
  - apiVersion: v2
    appVersion: 0.0.5
    created: "2023-01-13T02:42:00.508075646Z"
    dependencies:
    - condition: openldap.enabled
      name: openldap
      repository: '@stable'
      version: '>=1.2.4'
    description: cloud-native LDAP management service with a web interface
    digest: fc603b7f563b5fedd6d80411f24ff30318a2d6a6cca4ec40404af414ecec16d6
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Kubernetes_logo_without_workmark.svg/1280px-Kubernetes_logo_without_workmark.svg.png
    name: ldap-manager
    type: application
    urls:
    - https://romnn.github.io/ldap-manager/charts/ldap-manager-0.0.5.tgz
    version: 0.0.5
  ldapmanager:
  - apiVersion: v2
    appVersion: 0.0.0
    created: "2023-01-13T02:42:00.509041638Z"
    description: cloud-native LDAP management service with a web interface
    digest: b1d05800bd7dc8e4876cb7093a73f474e51322eb4e30a2dbc5528409f1f0445e
    icon: https://romnn.github.io/ldap-manager/icon/icon_lg.jpg
    name: ldapmanager
    type: application
    urls:
    - https://romnn.github.io/ldap-manager/charts/ldapmanager-0.0.0.tgz
    version: 0.0.0
generated: "2023-01-13T02:42:00.506369585Z"
