apiVersion: v1
entries:
  ldap-manager:
  - apiVersion: v2
    appVersion: 0.0.5
    created: "2023-03-06T18:52:01.945269274Z"
    dependencies:
    - condition: openldap.enabled
      name: openldap
      repository: '@stable'
      version: '>=1.2.4'
    description: cloud-native LDAP management service with a web interface
    digest: fc603b7f563b5fedd6d80411f24ff30318a2d6a6cca4ec40404af414ecec16d6
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Kubernetes_logo_without_workmark.svg/1280px-Kubernetes_logo_without_workmark.svg.png
    name: ldap-manager
    type: application
    urls:
    - https://romnn.github.io/ldap-manager/charts/ldap-manager-0.0.5.tgz
    version: 0.0.5
  ldapmanager:
  - apiVersion: v2
    appVersion: v0.0.33
    created: "2023-03-06T18:52:01.946719796Z"
    description: cloud-native LDAP management service with a web interface.
    digest: 02a219ec5c60d289878f0c52937bbaa8de332829cbce865cd714185fd12f3147
    home: https://github.com/romnn/ldap-manager
    icon: https://romnn.github.io/ldap-manager/icon/icon_lg.jpg
    keywords:
    - ldap
    - openldap
    - user-management
    - web
    maintainers:
    - name: romnn
      url: https://github.com/romnn/
    name: ldapmanager
    sources:
    - https://github.com/romnn/ldap-manager
    type: application
    urls:
    - https://romnn.github.io/ldap-manager/charts/ldapmanager-v0.0.33.tgz
    version: v0.0.33
generated: "2023-03-06T18:52:01.942782737Z"
