apiVersion: v1
entries:
  ldap-manager:
  - apiVersion: v2
    appVersion: 0.0.5
    created: "2023-03-05T13:22:10.497614353Z"
    dependencies:
    - condition: openldap.enabled
      name: openldap
      repository: '@stable'
      version: '>=1.2.4'
    description: cloud-native LDAP management service with a web interface
    digest: fc603b7f563b5fedd6d80411f24ff30318a2d6a6cca4ec40404af414ecec16d6
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Kubernetes_logo_without_workmark.svg/1280px-Kubernetes_logo_without_workmark.svg.png
    name: ldap-manager
    type: application
    urls:
    - https://romnn.github.io/ldap-manager/charts/ldap-manager-0.0.5.tgz
    version: 0.0.5
  ldapmanager:
  - apiVersion: v2
    appVersion: v0.0.31
    created: "2023-03-05T13:22:10.498765762Z"
    dependencies:
    - condition: openldap.enabled
      name: openldap
      repository: https://fluktuid.github.io/helm-charts/
      version: 0.1.1
    description: cloud-native LDAP management service with a web interface
    digest: 2f06c2cd02479bd5963156d789d0e84bdbe138833535f00a4343e93a22905c89
    icon: https://romnn.github.io/ldap-manager/icon/icon_lg.jpg
    name: ldapmanager
    type: application
    urls:
    - https://romnn.github.io/ldap-manager/charts/ldapmanager-v0.0.31.tgz
    version: v0.0.31
generated: "2023-03-05T13:22:10.496132542Z"
