apiVersion: v1
entries:
  ldapmanager:
  - apiVersion: v2
    appVersion: 0.0.26
    created: "2021-02-02T23:25:18.982765936Z"
    dependencies:
    - condition: openldap.enabled
      name: openldap
      repository: '@stable'
      version: '>=1.2.4'
    description: cloud-native LDAP management service with a web interface
    digest: 1dff475197c0360a7508d11d12ffeb7673c6b8a6dffce15da69ae1c930b14813
    icon: https://romnn.github.io/ldap-manager/icon/icon_lg.jpg
    name: ldapmanager
    type: application
    urls:
    - https://romnn.github.io/ldap-manager/charts/ldapmanager-0.0.26.tgz
    version: 0.0.26
generated: "2021-02-02T23:25:18.980990319Z"
