apiVersion: v1
entries:
  ldapmanager:
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2020-08-29T19:54:37.156895043Z"
    dependencies:
    - condition: openldap.enabled
      name: openldap
      repository: '@stable'
      version: '>=1.2.4'
    description: cloud-native LDAP management service with a web interface
    digest: 850c58addcc56624b792386ae7fe44b301413ad34144b2c4e06038e13d3bb3a0
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Kubernetes_logo_without_workmark.svg/1280px-Kubernetes_logo_without_workmark.svg.png
    name: ldapmanager
    type: application
    urls:
    - https://romnnn.github.io/ldap-manager/charts/ldapmanager-0.0.11.tgz
    version: 0.0.11
generated: "2020-08-29T19:54:37.154127522Z"
