apiVersion: v1
entries:
  ldap-manager:
  - apiVersion: v2
    appVersion: 0.0.5
    created: "2023-03-06T04:50:52.70359641Z"
    dependencies:
    - condition: openldap.enabled
      name: openldap
      repository: '@stable'
      version: '>=1.2.4'
    description: cloud-native LDAP management service with a web interface
    digest: fc603b7f563b5fedd6d80411f24ff30318a2d6a6cca4ec40404af414ecec16d6
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Kubernetes_logo_without_workmark.svg/1280px-Kubernetes_logo_without_workmark.svg.png
    name: ldap-manager
    type: application
    urls:
    - https://romnn.github.io/ldap-manager/charts/ldap-manager-0.0.5.tgz
    version: 0.0.5
  ldapmanager:
  - apiVersion: v2
    appVersion: v0.0.33
    created: "2023-03-06T04:50:52.705041529Z"
    dependencies:
    - condition: openldap.enabled
      name: openldap
      repository: https://fluktuid.github.io/helm-charts/
      version: 0.1.1
    description: cloud-native LDAP management service with a web interface
    digest: ff3e73d1aadab372d5da9f1d60e7df09b169d2b3ed17a1ad7afbc0cc74278d12
    icon: https://romnn.github.io/ldap-manager/icon/icon_lg.jpg
    name: ldapmanager
    type: application
    urls:
    - https://romnn.github.io/ldap-manager/charts/ldapmanager-v0.0.33.tgz
    version: v0.0.33
generated: "2023-03-06T04:50:52.701674585Z"
