apiVersion: v1
entries:
  ldap-manager:
  - apiVersion: v2
    appVersion: 0.0.5
    created: "2023-04-27T17:06:43.568653775Z"
    dependencies:
    - condition: openldap.enabled
      name: openldap
      repository: '@stable'
      version: '>=1.2.4'
    description: cloud-native LDAP management service with a web interface
    digest: fc603b7f563b5fedd6d80411f24ff30318a2d6a6cca4ec40404af414ecec16d6
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Kubernetes_logo_without_workmark.svg/1280px-Kubernetes_logo_without_workmark.svg.png
    name: ldap-manager
    type: application
    urls:
    - https://romnn.github.io/ldap-manager/charts/ldap-manager-0.0.5.tgz
    version: 0.0.5
  ldapmanager:
  - apiVersion: v2
    appVersion: v0.0.36
    created: "2023-04-27T17:06:43.571509456Z"
    dependencies:
    - condition: openldap.enabled
      name: openldap
      repository: ""
      version: '>=0.0.0'
    description: cloud-native LDAP management service with a web interface.
    digest: b2939d46f998140f4676406a705fa5672f6bea3dd1b0c12f617fc9033eb69dbc
    home: https://github.com/romnn/ldap-manager
    icon: https://romnn.github.io/ldap-manager/icon/icon_lg.jpg
    keywords:
    - ldap
    - openldap
    - user-management
    - web
    maintainers:
    - name: romnn
      url: https://github.com/romnn/
    name: ldapmanager
    sources:
    - https://github.com/romnn/ldap-manager
    type: application
    urls:
    - https://romnn.github.io/ldap-manager/charts/ldapmanager-v0.0.36.tgz
    version: v0.0.36
generated: "2023-04-27T17:06:43.567112085Z"
