apiVersion: v1
entries:
  ldap-manager:
  - apiVersion: v2
    appVersion: 0.0.5
    created: "2023-04-28T08:58:18.379855856Z"
    dependencies:
    - condition: openldap.enabled
      name: openldap
      repository: '@stable'
      version: '>=1.2.4'
    description: cloud-native LDAP management service with a web interface
    digest: fc603b7f563b5fedd6d80411f24ff30318a2d6a6cca4ec40404af414ecec16d6
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Kubernetes_logo_without_workmark.svg/1280px-Kubernetes_logo_without_workmark.svg.png
    name: ldap-manager
    type: application
    urls:
    - https://romnn.github.io/ldap-manager/charts/ldap-manager-0.0.5.tgz
    version: 0.0.5
  ldapmanager:
  - apiVersion: v2
    appVersion: v0.0.43
    created: "2023-04-28T08:58:18.382883149Z"
    dependencies:
    - condition: openldap.enabled
      name: openldap
      repository: ""
      version: '>=0.0.0'
    description: cloud-native LDAP management service with a web interface.
    digest: e71c36f137431242db2b66672358e00b576afc52161af334b7a57359c506cd31
    home: https://github.com/romnn/ldap-manager
    icon: https://romnn.github.io/ldap-manager/icon/icon_lg.jpg
    keywords:
    - ldap
    - openldap
    - user-management
    - web
    maintainers:
    - name: romnn
      url: https://github.com/romnn/
    name: ldapmanager
    sources:
    - https://github.com/romnn/ldap-manager
    type: application
    urls:
    - https://romnn.github.io/ldap-manager/charts/ldapmanager-v0.0.43.tgz
    version: v0.0.43
generated: "2023-04-28T08:58:18.378290108Z"
