version: "3.6"

services:
  openldap:
    image: osixia/openldap
    ports:
      - 389:389
      - 636:636
    environment:
      LDAP_ORGANISATION: Example Inc.
      LDAP_DOMAIN: example.org
      LDAP_BASE_DN: dc=example,dc=org

      LDAP_ADMIN_PASSWORD: admin
      LDAP_CONFIG_PASSWORD: config

      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: readonly
      LDAP_READONLY_USER_PASSWORD: readonly

      LDAP_TLS: "false"
      LDAP_RFC2307BIS_SCHEMA: "true"
    logging:
      # disable logging
      driver: none

  ldapmanager:
    image: romnn/ldap-manager:latest
    ports:
      - 80:80
      # uncomment if you want to expose the GRPC endpoint
      # - 9090:9090
    depends_on:
      - openldap
    environment:
      OPENLDAP_HOST: "openldap"
      OPENLDAP_PORT: 389

      OPENLDAP_ADMIN_PASSWORD: admin
      OPENLDAP_CONFIG_PASSWORD: config

      OPENLDAP_ORGANIZATION: Example Inc.
      OPENLDAP_DOMAIN: example.org
      OPENLDAP_BASE_DN: dc=example,dc=org

      DEFAULT_ADMIN_USERNAME: ldapadmin
      DEFAULT_ADMIN_PASSWORD: changeme
      FORCE_CREATE_ADMIN: "true"

      OPENLDAP_TLS: "false"
      OPENLDAP_USE_RFC2307BIS: "true"
      
      ISSUER: issuer@example.org
      AUDIENCE: example.org
      GENERATE: "true"

  screenshot:
    image: zenika/alpine-chrome:with-puppeteer
    command: ["sh", "-c", "npm install && node src/screenshot.js"]
    depends_on:
      - ldapmanager
    volumes:
      - ./screenshot/screenshot.js:/usr/src/app/src/screenshot.js:ro
      - ./screenshot/package.json:/usr/src/app/package.json:ro
      - ./screenshot/package-lock.json:/usr/src/app/package-lock.json:ro
      - ../screenshots:/usr/src/app/output
    cap_add:
      - SYS_ADMIN
    
