version: "3.6"

services:
  openldap:
    image: osixia/openldap
    ports:
      - 389:389
      - 636:636
    environment:
      LDAP_ORGANISATION: Example Inc.
      LDAP_DOMAIN: example.org
      LDAP_BASE_DN: dc=example,dc=org

      LDAP_ADMIN_PASSWORD: admin
      LDAP_CONFIG_PASSWORD: config

      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: readonly
      LDAP_READONLY_USER_PASSWORD: readonly

      LDAP_TLS: "false"
      LDAP_RFC2307BIS_SCHEMA: "true"
    logging:
      # disable logging
      driver: none

  ldapmanager:
    # you probably want to use the prebuild image
    # image: romnn/ldap-manager:latest
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 80:80
      # uncomment if you want to expose the GRPC endpoint
      # - 9090:9090
    depends_on:
      - openldap
    environment:
      HTTP_PORT: 80

      LDAP_HOST: "openldap"
      LDAP_PORT: 389

      LDAP_ADMIN_PASSWORD: admin
      LDAP_CONFIG_PASSWORD: config

      LDAP_ORGANIZATION: Example Inc.
      LDAP_DOMAIN: example.org
      DAP_BASE_DN: dc=example,dc=org

      DEFAULT_ADMIN_USERNAME: ldapadmin
      DEFAULT_ADMIN_PASSWORD: changeme
      FORCE_CREATE_ADMIN: "true"

      LDAP_TLS: "false"
      LDAP_USE_RFC2307BIS: "true"
      
      ISSUER: issuer@example.org
      AUDIENCE: example.org
      GENERATE: "true"

  screenshot:
    build:
      context: ../
      dockerfile: ./deployment/screenshot/Dockerfile
    environment:
      OUTPUT_DIR: "/output"
      LDAP_MANAGER_HOST: "ldapmanager"
      ADMIN_USERNAME: "ldapadmin"
      ADMIN_PASSWORD: "changeme"
    depends_on:
      - ldapmanager
    volumes:
      - ../screenshots:/output
    cap_add:
      - SYS_ADMIN
    
