version: "3.6"

services:
  openldap:
    image: osixia/openldap
    ports:
      - 389:389
      - 636:636
    environment:
      LDAP_ORGANISATION: Example Inc.
      LDAP_DOMAIN: example.org
      LDAP_BASE_DN: dc=example,dc=org

      LDAP_ADMIN_PASSWORD: admin
      LDAP_CONFIG_PASSWORD: config

      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: readonly
      LDAP_READONLY_USER_PASSWORD: readonly

      LDAP_TLS: "false"
      LDAP_RFC2307BIS_SCHEMA: "true"
    logging:
      # disable logging
      driver: none

  ldapmanager:
    # image: romnn/ldap-manager:latest
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 80:80
      # uncomment if you want to expose the GRPC endpoint
      # - 9090:9090
    depends_on:
      - openldap
    environment:
      HTTP_PORT: 80

      LDAP_HOST: "openldap"
      LDAP_PORT: 389

      LDAP_ADMIN_PASSWORD: admin
      LDAP_CONFIG_PASSWORD: config

      LDAP_ORGANIZATION: Example Inc.
      LDAP_DOMAIN: example.org
      DAP_BASE_DN: dc=example,dc=org

      DEFAULT_ADMIN_USERNAME: ldapadmin
      DEFAULT_ADMIN_PASSWORD: changeme
      FORCE_CREATE_ADMIN: "true"

      LDAP_TLS: "false"
      LDAP_USE_RFC2307BIS: "true"
      
      ISSUER: issuer@example.org
      AUDIENCE: example.org
      GENERATE: "true"

  screenshot:
    image: zenika/alpine-chrome:with-puppeteer
    # entrypoint: sh -c
    # mkdir -p ./app/deployment/screenshot 
    command: sh -c "cp -r ./app_tmp ./app && chmod -R 775 ./app && cd ./app/deployment/screenshot && ls -lia . && yarn install && ./node_modules/.bin/ts-node screenshot.ts"
    # command: sh -c "cp -p ./app/web && cp -r ./app_tmp/web ./app/web && cp -r ./app_tmp/deployment/screenshot ./app/deployment/screenshot && cd ./app/deployment/screenshot && ls -lia ."

      # ./app/deployment/screenshot/"
      # - && cd ./app/deployment/screenshot
      # - && yarn install
      # - && ts-node src/screenshot.ts
      # - sh
      # - -c
      # - chown -R chrome:chrome app/deployment/ && chmod -R 775 app/deployment/ && 
    # command: ["sh", "-c", "yarn install && ts-node src/screenshot.ts"]
    environment:
      OUTPUT_DIR: "/usr/src/app/output"
      LDAP_MANAGER_HOST: "ldapmanager"
      ADMIN_USERNAME: "ldapadmin"
      ADMIN_PASSWORD: "changeme"
    # depends_on:
    #   - ldapmanager
    volumes:
      - ../:/usr/src/app/app_tmp:ro
      # - ./screenshot/screenshot.ts:/usr/src/app/app/screenshot_tmp/screenshot.ts:ro
      # - ./screenshot/package.json:/usr/src/app/app/screenshot_tmp/package.json:ro
      # - ./screenshot/yarn.lock:/usr/src/app/app/screenshot_tmp/yarn.lock:ro
      # - ../web:/usr/src/app/app/web:ro
      - ../screenshots:/usr/src/app/output
    # volumes:
    #   - ./screenshot/screenshot.ts:/usr/src/app/app/src/screenshot.ts:ro
    #   - ./screenshot/package.json:/usr/src/app/app/package.json:ro
    #   - ./screenshot/yarn.lock:/usr/src/app/app/yarn.lock:ro
    #   - ../screenshots:/usr/src/app/app/output
    cap_add:
      - SYS_ADMIN
    
