# Default values for ldap-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ldap-manager:
  # see more available options in charts/ldap-manager/values.yaml
  ldap:
    host: ldap-manager-openldap
    adminPassword: admin
    configPassword: config
    readonly:
      user: readonly
      password: readonly
    organization: Example Inc.
    domain: example.org
    baseDN: dc=example,dc=org
    tls: "false"
    useRFC230BIS: "true"
  
  ingress:
    enabled: true
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    httpHosts:
      - host: ldapmanager.example.org
        paths: ["/"]
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  

openldap:
  enabled: true
  fullnameOverride: ldap-manager-openldap
  adminPassword: admin
  configPassword: config
  env:
    LDAP_ORGANISATION: Example Inc.
    LDAP_DOMAIN: example.org
    LDAP_BASE_DN: dc=example,dc=org
    LDAP_READONLY_USER: "true"
    LDAP_READONLY_USER_USERNAME: readonly
    LDAP_READONLY_USER_PASSWORD: readonly
    LDAP_TLS: "false"
    LDAP_RFC2307BIS_SCHEMA: "true"