{{- if .Values.persistence.enabled }}
{{- if not .Values.persistence.existingClaim }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
  name: {{ include "openldap.fullname" . }}
  {{- if .Values.persistence.resourcePolicy }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
  # Here we patch the PVC to avoid removal during a helm delete
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
  {{- end }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
spec:
  accessModes: 
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "100Mi" | quote }}
{{- if .Values.persistence.storageClass }}
{{- if eq "-" .Values.persistence.storageClass }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}
{{- end }}
{{- if .Values.persistence.volumeName }}
  volumeName: {{ .Values.persistence.volumeName | quote }}
{{- end }}
{{- end }}
{{- end }}
