{{ if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openldap.fullname" . }}-auth
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
type: Opaque
data:
  LDAP_ADMIN_PASSWORD: {{ .Values.auth.adminPassword | default (randAlphaNum 32) | b64enc | quote }}
  LDAP_CONFIG_PASSWORD: {{ .Values.auth.configPassword | default (randAlphaNum 32) | b64enc | quote }}
stringData:
  LDAP_HOST: {{ template "openldap.fullname" . }}
{{ end }}
