{{- if and .Values.openldap.enabled .Values.openldap.persistence.enabled .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
  name: {{ .Values.persistence.claimName }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
  # Here we patch the PVC to avoid removal during a helm delete
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
{{ include "ldapmanager.labels" . | indent 4 }}
    component: openldap
# The following config is identical to the default openldap config
{{- if .Values.openldap.extraLabels }}
{{ toYaml .Values.openldap.extraLabels | indent 4 }}
{{- end }}
spec:
  accessModes: 
    - {{ .Values.openldap.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.openldap.persistence.size | quote }}
  {{- if .Values.openldap.persistence.storageClass }}
    {{- if eq "-" .Values.openldap.persistence.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ .Values.openldap.persistence.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}