name: release
on:
  push:
    tags:
      - "*"

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint helm chart
        run: helm lint deployment/helm/charts/ldapmanager/

      - run: |
          echo "repo_user=$(echo ${GITHUB_REPOSITORY} | awk -F / '{print $1}' )" >> $GITHUB_ENV
          echo "repo_name=$(echo ${GITHUB_REPOSITORY} | awk -F / '{print $2}' )" >> $GITHUB_ENV

      - name: Package helm chart
        run: |
          touch ./public/.nojekyll
          deployment/helm/charts/ldapmanager/add-repos.sh
          helm package --dependency-update --destination ./public/charts deployment/helm/charts/ldapmanager
          helm repo index --url https://${{ env.repo_user }}.github.io/${{ env.repo_name }}/charts ./public/charts

      - name: Deploy to pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true

  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - id: query
        uses: romnnn/query-git-action@master

      - name: Compile binaries
        run: |
          pip install invoke
          go get -u github.com/mitchellh/gox
          invoke cc

      - name: Upload release binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*
          tag: ${{ steps.query.outputs.stable_semver_version }}
          release_name: Version ${{ steps.query.outputs.stable_semver_version }}
          overwrite: true
          file_glob: true
