name: lint
on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: install code check tools
        run: |
          go get -u golang.org/x/lint/golint
          go get -u github.com/fzipp/gocyclo/cmd/gocyclo
          go get -u github.com/mitchellh/gox
          # do not change go.mod and go.sum
          git checkout go.mod go.sum

      - name: code checks
        uses: pre-commit/action@v2.0.0
        with:
          extra_args: --all-files

  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint helm chart
        run: helm lint deployment/helm/charts/ldap-manager/

  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: |
          go build ./...
      - name: Test
        run: |
          go test -v -race -coverprofile=coverage.txt -coverpkg=all -covermode=atomic ./...
      - uses: codecov/codecov-action@v1
